function S7_summarize_compare_table()
% Summarize comparisons into a CCE-style table per algorithm
% Output:
%   results_compare/Table_compare.csv
%   results_compare/Table_compare.tex

    inDir = fullfile(pwd, "results_compare");
    load(fullfile(inDir, "raw_COMPARE.mat"), "raw");

    algoList = {'CSO','PSO','GA','JADE'};

    rows = {};

    for fi = 1:numel(raw)
        F = raw(fi).func_id;

        for a = 1:numel(algoList)
            algo = algoList{a};

            b  = raw(fi).(algo).baseline.best(:);
            k  = raw(fi).(algo).klsr.best(:);
            tb = raw(fi).(algo).baseline.time(:);
            tk = raw(fi).(algo).klsr.time(:);

            okb = isfinite(b)  & ~isnan(b);
            okk = isfinite(k)  & ~isnan(k);
            oktb= isfinite(tb) & ~isnan(tb);
            oktk= isfinite(tk) & ~isnan(tk);

            bm = median(b(okb));
            km = median(k(okk));

            if isfinite(bm) && bm ~= 0
                imp = (bm - km) / bm * 100;
            else
                imp = NaN;
            end

            bt = mean(tb(oktb));
            kt = mean(tk(oktk));

            rows(end+1,:) = {F, algo, bm, km, imp, bt, kt}; %#ok<AGROW>
        end
    end

    T = cell2table(rows, 'VariableNames', ...
        {'Func','Algo','Median_Baseline','Median_KLSR','ImprovePct','MeanTime_Baseline','MeanTime_KLSR'});

    outCsv = fullfile(inDir, "Table_compare.csv");
    writetable(T, outCsv);

    % ---- LaTeX table ----
    outTex = fullfile(inDir, "Table_compare.tex");
    fid = fopen(outTex, "w");
    fprintf(fid, "%% Auto-generated by S6_summarize_compare_table_CCE.m\n");
    fprintf(fid, "\\begin{table*}[t]\n\\centering\n");
    fprintf(fid, "\\caption{Comparative results of baseline optimizers and their KLSR-enhanced variants on CEC2017 ($D=50$, $R=10$).}\n");
    fprintf(fid, "\\label{tab:compare_main}\n");
    fprintf(fid, "\\begin{tabular}{ccrrrrr}\n\\toprule\n");
    fprintf(fid, "Func & Algo & Median(B) & Median(KLSR) & Improve(\\%%) & Time(B) & Time(KLSR) \\\\\n\\midrule\n");

    for i = 1:height(T)
        fprintf(fid, "F%02d & %s & %.3e & %.3e & %.2f & %.2f & %.2f \\\\\n", ...
            T.Func(i), T.Algo{i}, T.Median_Baseline(i), T.Median_KLSR(i), T.ImprovePct(i), ...
            T.MeanTime_Baseline(i), T.MeanTime_KLSR(i));
    end

    fprintf(fid, "\\bottomrule\n\\end{tabular}\n\\end{table*}\n");
    fclose(fid);

    disp(T(1:min(12,height(T)),:));
    fprintf("Saved: %s\n", outCsv);
    fprintf("Saved: %s\n", outTex);
end
