function S8_export_table_compare()
% Export ONE comparison table:
% For each function: Baseline vs KLSR for each algo, plus win/tie/loss symbols.
% Bottom row: +/=/- counts per algorithm.
%
% Input : results_compare/raw_COMPARE.mat
% Output: results_compare/Table4_compare.tex

    inDir = fullfile(pwd, "results_compare");
    load(fullfile(inDir, "raw_COMPARE.mat"), "raw");

    algoList = {'CSO','PSO','GA','JADE'};   % your 4 algos
    nA = numel(algoList);
    nF = numel(raw);

    % ---------- collect medians & signs ----------
    % medB(fi,a), medK(fi,a), signSym(fi,a) in {'+','=','-'}
    medB = nan(nF,nA);
    medK = nan(nF,nA);
    symb = repmat("=", nF, nA);

    for fi = 1:nF
        for a = 1:nA
            algo = algoList{a};

            b = raw(fi).(algo).baseline.best(:);
            k = raw(fi).(algo).klsr.best(:);

            b = b(isfinite(b) & ~isnan(b));
            k = k(isfinite(k) & ~isnan(k));

            medB(fi,a) = median(b);
            medK(fi,a) = median(k);

            % Wilcoxon signed-rank test (paired) on per-run results
            % H=1 means significant difference at alpha
            alpha = 0.05;

            % If lengths mismatch, align by min length (should not happen if you used same seeds)
            m = min(numel(b), numel(k));
            b2 = b(1:m); k2 = k(1:m);

            try
                p = signrank(b2, k2, 'alpha', alpha);
            catch
                % fallback if signrank not available / edge cases
                p = 1.0;
            end

            if p < alpha
                % Smaller is better. If KLSR median < baseline median => win (+)
                if medK(fi,a) < medB(fi,a)
                    symb(fi,a) = "+";
                elseif medK(fi,a) > medB(fi,a)
                    symb(fi,a) = "-";
                else
                    symb(fi,a) = "=";
                end
            else
                symb(fi,a) = "=";
            end
        end
    end

    % win/tie/loss counts
    cntPlus  = sum(symb=="+", 1);
    cntEq    = sum(symb=="=", 1);
    cntMinus = sum(symb=="-", 1);

    % ---------- LaTeX formatting helpers ----------
    fmtSci = @(x) format_sci(x);

    outTex = fullfile(inDir, "Table4_compare_like_CCE.tex");
    fid = fopen(outTex, "w");
    assert(fid~=-1, "Cannot write: %s", outTex);

    % ---------- write table ----------
    fprintf(fid, "%% Auto-generated by S8_export_table_compare.m\n");
    fprintf(fid, "\\begin{table*}[t]\n");
    fprintf(fid, "  \\centering\n");
    fprintf(fid, "  \\caption{Performance comparison of baseline vs. KLSR-enhanced algorithms on CEC2017 benchmark (D=50).}\n");
    fprintf(fid, "  \\label{tab:compare_table4}\n");
    fprintf(fid, "  \\setlength{\\tabcolsep}{5pt}\n");
    fprintf(fid, "  \\renewcommand{\\arraystretch}{1.05}\n");
    fprintf(fid, "  \\begin{tabular}{c");
    for a=1:nA
        fprintf(fid, "cc c"); % Baseline, KLSR, symbol
    end
    fprintf(fid, "}\n");
    fprintf(fid, "  \\toprule\n");

    % header row 1 (algo names)
    fprintf(fid, "  \\multirow{2}{*}{\\textbf{Func.}}");
    for a=1:nA
        fprintf(fid, " & \\multicolumn{3}{c}{\\textbf{%s}}", algoList{a});
    end
    fprintf(fid, " \\\\\n");

    % header row 2 (Baseline/KLSR/blank for symbol)
    fprintf(fid, "  ");
    for a=1:nA
        fprintf(fid, " & \\textbf{Baseline} & \\textbf{KLSR} & ");
    end
    fprintf(fid, "\\\\\n");

    % cmidrules
    fprintf(fid, "  \\cmidrule(lr){2-%d}\n", 1+3*nA);

    % body rows
    for fi = 1:nF
        F = raw(fi).func_id;
        fprintf(fid, "  F%02d", F);

        for a=1:nA
            fprintf(fid, " & %s & %s & %s", fmtSci(medB(fi,a)), fmtSci(medK(fi,a)), symb(fi,a));
        end
        fprintf(fid, " \\\\\n");
    end

    fprintf(fid, "  \\midrule\n");
    % +/-/= row
    fprintf(fid, "  \\textbf{$+$/=$-$}");
    for a=1:nA
        fprintf(fid, " & \\multicolumn{3}{c}{\\textbf{%d/%d/%d}}", cntPlus(a), cntEq(a), cntMinus(a));
    end
    fprintf(fid, " \\\\\n");

    fprintf(fid, "  \\bottomrule\n");
    fprintf(fid, "  \\end{tabular}\n");
    fprintf(fid, "  \\\\\n");
    fprintf(fid, "  \\vspace{2pt}\n");
    fprintf(fid, "  {\\footnotesize Note: Median best fitness over $R=10$ runs. Symbols: $+$ (win), $=$ (tie), $-$ (loss) based on Wilcoxon signed-rank test ($p<0.05$).}\n");
    fprintf(fid, "\\end{table*}\n");

    fclose(fid);

    fprintf("Saved: %s\\n", outTex);
end

function s = format_sci(x)
    % Format
    if ~isfinite(x)
        s = "NaN";
        return;
    end
    if x == 0
        s = "0";
        return;
    end
    e = floor(log10(abs(x)));
    m = x / 10^e;
    % 3 sig figs
    s = sprintf('%.3gE%+03d', m, e);
end
